#!/bin/bash
######################################
read -p "Enter y or n: " ANSWER
case "$ANSWER" in
[Yy])
    echo "You type y"
    ;;
[Nn])
    echo "You type n"
    ;;
*)
    echo "Invalid answer."
    ;;
esac
#####################################
case "$CHOICE" in
    1)
        df -h
        ;;
    2)
        uptime
        ;;
    *)
        break
        ;;
    esac
done
#####################################
